name: mssql-2019-cis
title: CIS Microsoft SQL Server 2019 Benchmark
maintainer: InSpec Compliance Team
copyright: Copyright 2024
license: Apache-2.0
summary: InSpec profile for CIS Microsoft SQL Server 2019 compliance
version: 1.0.0

inputs:
  - name: usernm
    description: MSSQL username
    type: string
  - name: passwd
    description: MSSQL password
    sensitive: true
    type: string
  - name: hostnm
    description: MSSQL host address
    type: string
  - name: port
    description: MSSQL port
    type: numeric
    value: 1433
  - name: servicenm
    description: MSSQL service/instance name
    type: string
    value: ""
