---
all:
  children:
    runner:
      hosts:
        azure_runner:
          ansible_host: 40.114.45.75
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/inspec_azure
          ansible_python_interpreter: /usr/bin/python3.9
          mssql_password: 'FCmGkCGWbmyxqrffStr0ng\!'
